version: '3.8'

services:
    db:
        image: postgres:17-alpine
        ports:
            - "5431:5432"
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234

    keycloak:
        image: quay.io/keycloak/keycloak:24.0.2
        ports:
            - "9090:8080"
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        volumes:
            - keycloak-data:/opt/keycloak/data
        command:
            - start-dev
            - --db=dev-file

volumes:
    keycloak-data:
        driver: local